#!/usr/bin/env python3
"""
plot_atlas_optical_accel_deltav.py

Generate a 3-panel diagnostic figure showing:
1) Optical acceleration proxy
2) Calibrated physical acceleration (m/s²)
3) Cumulative Δv (m/s)

Input: I3_Optical_Acceleration_DeltaV.csv
       (generated by atlas_delta_v_from_optical_proxy.py)

Output: I3_Optical_Acceleration_DeltaV_Figure.png

Author: Salah-Eddin Gherbi
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# -------------------------------------------------------------------
# CONFIG
# -------------------------------------------------------------------
CSV_FILE = "I3_Optical_Acceleration_DeltaV.csv"
OUT_FIG = "I3_Optical_Acceleration_DeltaV_Figure.png"

# -------------------------------------------------------------------
# LOAD
# -------------------------------------------------------------------
df = pd.read_csv(CSV_FILE)
df["date"] = pd.to_datetime(df["date"], utc=True)

# Use days_from_perihelion for the x-axis
x = df["days_from_perihelion"]

# -------------------------------------------------------------------
# FIGURE
# -------------------------------------------------------------------
plt.style.use("seaborn-v0_8-darkgrid")  # clean style

fig, axes = plt.subplots(3, 1, figsize=(10, 12), sharex=True)
fig.suptitle("3I/ATLAS Optical Acceleration & Δv Accumulation", fontsize=16)

# -------------------------------------------------
# Panel 1: Proxy
# -------------------------------------------------
ax = axes[0]
ax.plot(
    x,
    df["accel_proxy_scaled"],
    color="tab:blue",
    lw=1.8,
    label="Optical Acceleration Proxy (scaled)"
)
ax.axhline(0, color="black", lw=0.8, alpha=0.5)
ax.set_ylabel("Proxy (dimensionless)")
ax.legend(loc="upper left")

# -------------------------------------------------
# Panel 2: Physical acceleration
# -------------------------------------------------
ax = axes[1]
ax.plot(
    x,
    df["accel_m_s2"],
    color="tab:green",
    lw=1.8,
    label="Calibrated Acceleration $a(t)$ (m/s²)"
)
ax.axhline(0, color="black", lw=0.8, alpha=0.5)
ax.set_ylabel("$a(t)$ [m/s²]")
ax.legend(loc="upper left")

# -------------------------------------------------
# Panel 3: Cumulative Delta-v
# -------------------------------------------------
ax = axes[2]
ax.plot(
    x,
    df["cum_delta_v_m_s"],
    color="tab:red",
    lw=2.0,
    label="Cumulative Δv(t) (m/s)"
)
ax.set_ylabel("Cumulative Δv [m/s]")
ax.set_xlabel("Days from Perihelion (2025-10-29)")
ax.legend(loc="upper left")

# Mark perihelion (day = 0)
for ax in axes:
    ax.axvline(0, color="black", lw=1.0, linestyle="--", alpha=0.6)
    ax.text(0.5, 0.9, "Perihelion", transform=ax.transAxes,
            ha="left", va="center", fontsize=10, color="black")

plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig(OUT_FIG, dpi=300)
print(f"[INFO] Saved figure to {OUT_FIG}")
plt.close()
